# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='support/attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
