# Generated by ChatGPT
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_supportmessage_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={
                'ordering': ['created_at'],
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
            },
        ),
        migrations.AlterModelOptions(
            name='supportthread',
            options={
                'ordering': ['-updated_at'],
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
            },
        ),
        migrations.AddField(
            model_name='supportthread',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_support_threads',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Ответственный администратор',
            ),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='attachment',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='support/attachments/%Y/%m/',
                verbose_name='Вложение',
            ),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='support_messages',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор',
            ),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='is_from_staff',
            field=models.BooleanField(default=False, verbose_name='Ответ администратора'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='thread',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='support.supportthread',
                verbose_name='Диалог',
            ),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя посетителя'),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name='Идентификатор',
            ),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Обращение закрыто'),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='session_key',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                verbose_name='Ключ сессии',
            ),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='support_threads',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
