# Generated by Django 3.1 on 2025-12-20 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Имя гостя')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон гостя')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('P', 'Ожидает подтверждения'), ('C', 'Подтверждена'), ('X', 'Отменена'), ('D', 'Выполнена')], default='P', max_length=1)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод на карту')], default='cash', max_length=16)),
                ('payment_status', models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает подтверждения записи'), ('awaiting_payment', 'Ожидает оплаты'), ('awaiting_confirmation', 'Чек на проверке'), ('paid', 'Оплачено'), ('refund_requested', 'Ожидает возврата'), ('refunded', 'Возврат выполнен')], default='not_required', max_length=24)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='payment_receipts/')),
                ('receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_cardholder_name', models.CharField(blank=True, max_length=120)),
                ('refund_card_number', models.CharField(blank=True, max_length=64)),
                ('refund_card_type', models.CharField(blank=True, max_length=64)),
                ('refund_requested_at', models.DateTimeField(blank=True, null=True)),
                ('refund_receipt', models.ImageField(blank=True, null=True, upload_to='refund_receipts/')),
                ('refund_receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='category_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корзина товаров',
                'verbose_name_plural': 'Корзины товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('is_pickup', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('in_delivery', 'В доставке'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('paid', 'Оплачен')], default='created', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод на карту')], default='cash', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ товаров',
                'verbose_name_plural': 'Заказы товаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_salon/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photo_salon/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photo_salon/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photo_salon/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photo_salon/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('', 'Не указано'), ('male', 'Мужской'), ('female', 'Женский'), ('both', 'Обе')], max_length=10, null=True, verbose_name='Тип салона')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('subscription_expires_at', models.DateField(blank=True, help_text='Если не указано, салон будет активен без ограничения', null=True, verbose_name='Подписка действует до')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='booking.city')),
            ],
            options={
                'ordering': ['-position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.category')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='booking.salon')),
            ],
            options={
                'verbose_name': 'Услуга салона',
                'verbose_name_plural': 'Услуги салона',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='Фото услуги')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram Username')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat_id')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='stylists/', verbose_name='Фото')),
                ('show_client_phone', models.BooleanField(default=True, verbose_name='Показывать номер клиента в дашборде')),
                ('allow_cancel_appointment', models.BooleanField(default=True, verbose_name='Разрешить отмену записей')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='StylistLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='booking.stylist', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Рабочий интервал',
                'verbose_name_plural': 'Рабочие интервалы',
                'ordering': ['stylist', 'weekday', 'start_time'],
                'unique_together': {('stylist', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='StylistService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, сум')),
                ('salon_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.salonservice')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to='booking.stylist')),
            ],
            options={
                'verbose_name': 'Цена услуги мастера',
                'verbose_name_plural': 'Цены услуг мастеров',
                'unique_together': {('stylist', 'salon_service')},
            },
        ),
        migrations.AddField(
            model_name='stylist',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.stylistlevel'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylists', to='booking.salon'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='booking.service'),
        ),
        migrations.CreateModel(
            name='SalonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salon_products/', verbose_name='Фото товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка, %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Товар активен')),
                ('is_promoted', models.BooleanField(default=False, help_text='Только суперпользователь может включить или выключить рекламу.', verbose_name='Рекламировать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='booking.productcategory', verbose_name='Категория')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='booking.salon')),
            ],
            options={
                'verbose_name': 'Товар салона',
                'verbose_name_plural': 'Товары салона',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonPaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('uzcard', 'UZCARD'), ('humo', 'HUMO'), ('visa', 'VISA'), ('mastercard', 'Mastercard'), ('mir', 'МИР'), ('other', 'Другая')], default='other', max_length=32)),
                ('cardholder_name', models.CharField(max_length=120)),
                ('card_number', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to='booking.salon')),
            ],
            options={
                'verbose_name': 'Карта салона',
                'verbose_name_plural': 'Карты салона',
                'ordering': ['-is_active', '-updated_at'],
                'unique_together': {('salon', 'card_number')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.productorder')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.AddField(
            model_name='productorder',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='booking.salonpaymentcard'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='booking.salon'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.productcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='booking.salonproduct')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
            },
        ),
        migrations.AddField(
            model_name='productcart',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_carts', to='booking.salon'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FavoriteSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='booking.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный салон',
                'verbose_name_plural': 'Избранные салоны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало перерыва')),
                ('end_time', models.TimeField(verbose_name='Конец перерыва')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='booking.workinghour', verbose_name='Рабочий интервал')),
            ],
            options={
                'verbose_name': 'Перерыв',
                'verbose_name_plural': 'Перерывы',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.appointment')),
                ('stylist_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.stylistservice')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.salonpaymentcard'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.stylist', verbose_name='Мастер'),
        ),
        migrations.CreateModel(
            name='StylistDayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.stylist')),
            ],
            options={
                'unique_together': {('stylist', 'date', 'from_time', 'to_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='salonservice',
            unique_together={('salon', 'service')},
        ),
        migrations.AddIndex(
            model_name='productcart',
            index=models.Index(fields=['session_key'], name='booking_pro_session_4448e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritesalon',
            unique_together={('user', 'salon')},
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status='X'), fields=('stylist', 'start_time'), name='unique_active_appointment_per_slot'),
        ),
    ]
