# Generated by Django 3.1 on 2025-10-15 16:42

from django.db import migrations, models


def populate_card_holder_snapshot(apps, schema_editor):
    Appointment = apps.get_model('booking', 'Appointment')
    for appointment in Appointment.objects.select_related('payment_card').all():
        card = getattr(appointment, 'payment_card', None)
        holder = getattr(card, 'card_holder', '') if card else ''
        if holder and appointment.payment_card_holder_snapshot != holder:
            appointment.payment_card_holder_snapshot = holder
            appointment.save(update_fields=['payment_card_holder_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_card_holder_snapshot',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status='X'), fields=('stylist', 'start_time'), name='unique_active_appointment_per_slot'),
        ),
        migrations.RunPython(populate_card_holder_snapshot, migrations.RunPython.noop),
    ]
